from __future__ import annotations

__all__ = ["KVStorage"]


class KVStorage:
    def __init__(self, path: str) -> None: ...
    def get(self, key: str) -> str | None: ...
    def set(self, key: str, value: str) -> None: ...
    def has(self, key: str) -> bool: ...
