from __future__ import annotations

from collections.abc import Mapping, Sequence

__all__ = ["Feed", "FeedStorage", "Labels"]


class Labels:
    def __init__(self) -> None: ...
    def get(self, key: str, /) -> str | None: ...
    def put(self, key: str, val: str, /) -> None: ...
    @staticmethod
    def from_map(source: Mapping[str, str], /) -> Labels: ...
    def map(self) -> dict[str, str] | None: ...
    def watch(self) -> None: ...
    def watch_str(self) -> str: ...


class Feed:
    id: int
    time: int

    def __init__(self, time: int, /) -> None: ...
    @staticmethod
    def from_dict(labels: Mapping[str, str], time: int, /) -> Feed: ...
    def get_labels(self) -> Labels: ...
    def set_labels(self, source: Labels, /) -> None: ...


class FeedStorage:
    def __init__(self, manifest_path: str | None = None, window: int | None = None) -> None: ...  # audit:rust-bridge
    @staticmethod
    def open(manifest_path: str | None = None, window: int | None = None) -> FeedStorage: ...  # audit:rust-bridge
    def append(self, feeds: list[Feed], /) -> None: ...
    def vector_insert(self, id: int, vector: Sequence[float], /) -> bool: ...
    def query(
        self,
        f: tuple[str, Sequence[str] | None] | None,
        s2e: tuple[int | None, int | None],
        mode: bool,
        limit: int | None,
        /,
    ) -> list[int]: ...
    def vector_query(
        self,
        vector: Sequence[float],
        s2e: tuple[int | None, int | None],
        limit: int | None,
        /,
    ) -> list[int]: ...
    def get_feeds(self, ids: Sequence[int], /) -> list[Feed] | None: ...
